language: go

matrix:
  include:
    - go: 1.4.2
      install:
        - go get golang.org/x/tools/cmd/cover
        - go get golang.org/x/tools/cmd/vet
  include:
    - go: 1.5.2

script:
- ./test

notifications:
  email: false

sudo: false
